"""
Vaidya — Phase 4: DPO fine-tuning on top of Phase 2 QLoRA checkpoint.

Loads base model + Phase 2 LoRA adapter, trains with DPOTrainer on
preference pairs generated by generate_dpo_pairs.py.

Usage:
    python dpo_train.py --sft-run-name run3 --run-name dpo-run1
"""

__version__ = "1.0"

import os, sys, json, argparse, logging, time
from pathlib import Path

os.environ.setdefault("CUDA_VISIBLE_DEVICES", "0")
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

import torch
import mlflow
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, PeftModel
from trl import DPOTrainer, DPOConfig

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "layer2_finetune"))
import qlora_config as C

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--sft-run-name", default="run3", help="Phase 2 checkpoint to build on")
    p.add_argument("--run-name",     default="dpo-run1", help="Name for this DPO run")
    return p.parse_args()


def setup_credentials():
    if os.environ.get("KAGGLE_KERNEL_RUN_TYPE"):
        from kaggle_secrets import UserSecretsClient
        s = UserSecretsClient()
        os.environ["AWS_ACCESS_KEY_ID"]     = s.get_secret("AWS_ACCESS_KEY_ID")
        os.environ["AWS_SECRET_ACCESS_KEY"] = s.get_secret("AWS_SECRET_ACCESS_KEY")
        os.environ["AWS_DEFAULT_REGION"]    = s.get_secret("AWS_DEFAULT_REGION")


def setup_mlflow():
    mlflow.set_tracking_uri("./mlruns")
    try:
        mlflow.create_experiment("vaidya-dpo",
                                 artifact_location=f"{C.S3_BUCKET}/mlflow")
    except Exception:
        pass
    mlflow.set_experiment("vaidya-dpo")


def load_dpo_pairs() -> Dataset:
    pairs_path = Path("dpo_pairs.jsonl")
    if not pairs_path.exists():
        log.info("Downloading dpo_pairs.jsonl from S3...")
        import boto3
        s3 = boto3.client("s3")
        bucket = C.S3_BUCKET.replace("s3://", "")
        s3.download_file(bucket, "data/dpo_pairs.jsonl", str(pairs_path))

    rows = [json.loads(l) for l in pairs_path.read_text().splitlines()]
    ds = Dataset.from_list(rows)
    log.info("DPO pairs loaded: %d", len(ds))
    return ds


def load_model(sft_run_name: str):
    cc = torch.cuda.get_device_capability()
    dtype = torch.bfloat16 if cc[0] >= 8 else torch.float16

    bnb_cfg = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=dtype,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
    )
    model = AutoModelForCausalLM.from_pretrained(
        C.MODEL_ID,
        quantization_config=bnb_cfg,
        device_map={"": 0},
    )
    model = prepare_model_for_kbit_training(
        model,
        use_gradient_checkpointing=True,
        gradient_checkpointing_kwargs={"use_reentrant": False},
    )

    # Load Phase 2 SFT adapter first
    adapter_dir = Path(f"./checkpoints/{sft_run_name}")
    if not adapter_dir.exists():
        log.info("SFT adapter not found locally — downloading from S3...")
        import boto3
        s3 = boto3.client("s3")
        bucket = C.S3_BUCKET.replace("s3://", "")
        adapter_dir.mkdir(parents=True, exist_ok=True)
        paginator = s3.get_paginator("list_objects_v2")
        for page in paginator.paginate(Bucket=bucket, Prefix=f"checkpoints/{sft_run_name}/"):
            for obj in page.get("Contents", []):
                key  = obj["Key"]
                fname = key.split("/", 2)[-1]
                dest  = adapter_dir / fname
                dest.parent.mkdir(parents=True, exist_ok=True)
                s3.download_file(bucket, key, str(dest))

    model = PeftModel.from_pretrained(model, str(adapter_dir), is_trainable=True)
    log.info("Loaded SFT adapter from %s", adapter_dir)

    tokenizer = AutoTokenizer.from_pretrained(C.MODEL_ID)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    return model, tokenizer


def train(args, model, tokenizer, dataset):
    cc = torch.cuda.get_device_capability()
    use_bf16 = cc[0] >= 8
    run_dir = Path("./checkpoints") / args.run_name

    dpo_cfg = DPOConfig(
        output_dir=str(run_dir),
        beta=0.1,
        max_length=512,
        max_prompt_length=256,
        per_device_train_batch_size=2,
        gradient_accumulation_steps=8,   # effective batch = 16
        num_train_epochs=1,
        learning_rate=5e-5,
        lr_scheduler_type="cosine",
        warmup_ratio=0.1,
        bf16=use_bf16,
        fp16=not use_bf16,
        gradient_checkpointing=True,
        gradient_checkpointing_kwargs={"use_reentrant": False},
        logging_steps=20,
        save_strategy="steps",
        save_steps=100,
        save_total_limit=2,
        report_to="mlflow",
        run_name=f"vaidya-dpo-{args.run_name}",
    )

    trainer = DPOTrainer(
        model=model,
        args=dpo_cfg,
        processing_class=tokenizer,
        train_dataset=dataset,
    )

    with mlflow.start_run(run_name=f"vaidya-dpo-{args.run_name}"):
        mlflow.log_params({
            "sft_run":        args.sft_run_name,
            "beta":           dpo_cfg.beta,
            "n_pairs":        len(dataset),
            "learning_rate":  dpo_cfg.learning_rate,
            "precision":      "bf16" if use_bf16 else "fp16",
        })

        t0 = time.time()
        result = trainer.train()
        elapsed = time.time() - t0

        mlflow.log_metrics({
            "final_train_loss":  result.training_loss,
            "train_runtime_sec": elapsed,
        })

        trainer.save_model(str(run_dir))
        tokenizer.save_pretrained(str(run_dir))
        log.info("DPO checkpoint saved → %s", run_dir)

    return run_dir


def push_to_s3(run_dir: Path, run_name: str):
    import boto3
    s3 = boto3.client("s3")
    bucket = C.S3_BUCKET.replace("s3://", "")
    uploaded = 0
    for f in run_dir.rglob("*"):
        if f.is_file():
            key = f"checkpoints/{run_name}/{f.relative_to(run_dir).as_posix()}"
            s3.upload_file(str(f), bucket, key)
            uploaded += 1
    log.info("Uploaded %d files → %s/checkpoints/%s/", uploaded, C.S3_BUCKET, run_name)

    mlruns_dir = Path("mlruns")
    if mlruns_dir.exists():
        for f in mlruns_dir.rglob("*"):
            if f.is_file():
                key = f"mlflow/{f.relative_to('.').as_posix()}"
                s3.upload_file(str(f), bucket, key)


def main():
    args = parse_args()
    log.info("dpo_train.py v%s  |  sft=%s  run=%s", __version__, args.sft_run_name, args.run_name)
    setup_credentials()
    setup_mlflow()

    dataset        = load_dpo_pairs()
    model, tokenizer = load_model(args.sft_run_name)
    run_dir          = train(args, model, tokenizer, dataset)

    try:
        push_to_s3(run_dir, args.run_name)
    except Exception as e:
        log.warning("S3 upload failed: %s", e)

    log.info("✅ Phase 4 DPO complete.")
    log.info("   Checkpoint : %s/checkpoints/%s/", C.S3_BUCKET, args.run_name)
    log.info("   Next       : run merge_adapter.py --dpo-run-name %s", args.run_name)


if __name__ == "__main__":
    main()
